// exception is a error 
// how to handel that exception try() catch()


class Main 
{
    public static void main(String[] args)
    {
        try
        {
        int a=10;
        int b=0;
        
        int c=a/b;
        
        System.out.println(c);
        }
        
        catch(Exception e)
        {
            System.out.println(e.getMessage());
        }
        finally
        {
            System.out.println("i will run always wheathere exception found or not");
        }
        System.out.println("this is very important programme");
    }
}